### ISSUE TITLE
Exception while building initial playlist

### ISSUE THREAD

**Issue by After-Shock** [l3uddz/ss-tvirl#17]
Receiving this issue when attempting to restart the ./ss-tvirl.py

I've cleared the token and it grabs a new one without issue.  Parsing/building the initial playlist seems to error out.  Not sure if something changed on the SS side of things this week, either FOG or etc.  Worked fine for weeks, besides the occasional Token replacement getting stuck.  (What's changed?)  Nothing, not the server, or the IP or the account.  It's not authorization as it grabs a fresh token so I'm guessing somethings changed on the playlist grab side of things.

Any help and insight before NFL kickoff this weekend would be greatly appreciated.  Thanks!

```2018-09-05 07:48:26,393 - INFO       - ss-tvirl-plexdvr -  <module>                 - Initializing
2018-09-05 07:48:26,394 - DEBUG      - ss-tvirl-plexdvr -  load_token               - Loaded token u'c2WU9OS81LzIwMTggMTA6MzM6MjkgQU0maGFzaF92YWx1ZT1YMUVEeWZzdUthd2dWZFdxaHhpNVdRPT0mdmFsaWRtaW51dGVzPTI0MCZpZD3LTI1MDc=', expires at 2018-09-05 10:33:29.791592
2018-09-05 07:48:26,399 - INFO       - ss-tvirl-plexdvr -  <module>                 - Building initial playlist...
2018-09-05 07:48:26,399 - DEBUG      - ss-tvirl-plexdvr -  build_playlist           - Loading feed from SmoothStreams
2018-09-05 07:48:28,538 - INFO       - ss-tvirl-plexdvr -  fetch_xmltv_gzip         - Loading compressed epg from SmoothStreams
2018-09-05 07:48:28,886 - INFO       - ss-tvirl-plexdvr -  fetch_xmltv_gzip         - Decompressed xmltv5.xml.gz
2018-09-05 07:48:29,907 - INFO       - ss-tvirl-plexdvr -  fog_to_plex_epg          - Processing fog epg to plex epg
2018-09-05 07:48:29,919 - ERROR      - ss-tvirl-plexdvr -  <module>                 - Exception while building initial playlist: 
Traceback (most recent call last):
  File "./ss-tvirl.py", line 420, in <module>
    playlist = build_playlist()
  File "./ss-tvirl.py", line 216, in build_playlist
    chan_map = build_channel_map()
  File "./ss-tvirl.py", line 197, in build_channel_map
    resp = fetch_xmltv_gzip()
  File "./ss-tvirl.py", line 169, in fetch_xmltv_gzip
    plex_xmltv = fog_to_plex_epg(data)
  File "./ss-tvirl.py", line 189, in fog_to_plex_epg
    a.attrib['channel'] = chan_map[a.attrib['channel']]
KeyError: 'None'
```

**Comment by After-Shock** [comment]
Appears the remote issue was fixed, it had nothing to do with this script as it magically started working again.
