### ISSUE TITLE
Not too sure --- ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by tempt3d** [l3uddz/ss-tvirl#3]
Working flawless until yesterday when it started throwing this error... help?

ubuntu 16.04

[2017-09-10 08:56:19,097] ERROR in app: Exception on /sstv/playlist.m3u8 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./ss-tvirl.py", line 200, in bridge
    playlist = get_playlist()
  File "./ss-tvirl.py", line 141, in get_playlist
    return remap_playlist(resp)
  File "./ss-tvirl.py", line 148, in remap_playlist
    resp = loads(urlopen(url).read().decode("utf-8"))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by l3uddz** [comment]
pushed an update that should hopefully solve this. close the issue if it does

**Comment by tempt3d** [comment]
thanks!
