### ISSUE TITLE
script fails to run

### ISSUE THREAD

**Issue by tenzone** [l3uddz/ss-tvirl#6]
so i recently pulled the newest version of the script, and now i cant get it to run, here is what i get when running the sstv.py:

` tenz@tools  /opt/sstv  python ss-tvirl.py
2017-10-06 20:03:08,387 - INFO       - ss-tvirl   -  <module>                 - Initializing
2017-10-06 20:03:08,387 - DEBUG      - ss-tvirl   -  load_token               - Loaded token u'c2VydmVyX3RpbWU9MTAvNi8yMDE3IDExOjUyOjAzIFBNJmhhc2hfdmFsdWU9TzFVR0ZlK3YwdjdnQkthNEN1Y3dZZz09JnZhbGlkbWludXRlcz0yNDAmaWQ9dmlld21zLTE0Mzg=', expires at 2017-10-06 23:52:03.252096
2017-10-06 20:03:08,390 - INFO       - ss-tvirl   -  <module>                 - Building initial playlist...
2017-10-06 20:03:08,391 - DEBUG      - ss-tvirl   -  build_playlist           - Loading feed from SmoothStreams
2017-10-06 20:03:08,475 - DEBUG      - ss-tvirl   -  build_channel_map        - Loading epg from fog
2017-10-06 20:03:08,556 - ERROR      - ss-tvirl   -  <module>                 - Exception while building initial playlist:
Traceback (most recent call last):
  File "ss-tvirl.py", line 241, in <module>
    playlist = build_playlist()
  File "ss-tvirl.py", line 157, in build_playlist
    chan_map = build_channel_map()
  File "ss-tvirl.py", line 144, in build_channel_map
    xml = ET.fromstring(resp)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0`

i tried removing the later version of requests and putting 2.10.0, same thing.

**Comment by dbowles1975** [comment]
Same thing here. There's changes being made to the channel lineup as we speak. I'm sure this is related.

**Comment by tenzone** [comment]
Cool.   Will wait till that pans out and see how everything ends up.  Thanks for the heads up

**Comment by tenzone** [comment]
looks as if it is back working now.  ill close this issue and re-open if needed.  thanks
